### ISSUE TITLE
TypeScript check failed

### ISSUE THREAD

**Issue by recallwei** [delucis/astro-auto-import#14]
![image](https://user-images.githubusercontent.com/62941121/232238045-15df5114-2cf0-4d03-b3ca-78b8e7eb6c80.png)
Cannot find the astro component.

**Comment by recallwei** [comment]
Maybe it should generate a .d.ts file automatically?

**Comment by delucis** [comment]
I actually explored type generation previously — work is in this branch: https://github.com/delucis/astro-auto-import/tree/type-generation

In general I’m not convinced auto-importing is a best practice inside `.astro` files, so that was a big reason I decided against including type generation in the main release. While I think it can be handy in content files (like MDX), I’d advise against using an auto-import in `.astro` and to prefer an explicit `import` instead.

**Comment by delucis** [comment]
I’m going to drop support for use of auto imports in `.astro` files in the next release — only MDX will be supported. MDX isn’t type checked, so I’ll close this issue.
